import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Xbox Games",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-blue-600 text-white p-4">
          <div className="flex space-x-4">
            <Link href="/" className="hover:underline">Home</Link>
            <Link href="/apiinfo" className="hover:underline">API Info</Link>
            <Link href="/games" className="hover:underline">Games</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
